export enum UploadStateEnum {
  NOT_STARTED = 'NOT_STARTED',
  VALIDATING = 'VALIDATING',
  LOOKING_FOR_EXCEL_DUPLICATES = 'LOOKING_FOR_EXCEL_DUPLICATES',
  LOOKING_FOR_DUPLICATES = 'LOOKING_FOR_DUPLICATES',
  UPLOADING = 'UPLOADING',
  FINISHED = 'FINISHED',
}
